[package]
name = "timer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
strum = { version = "0.27.2", features = ["derive"] }
strum_macros = "0.27.2"
